# Generated by Django 5.0.3 on 2024-04-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='criticality',
            field=models.CharField(default='low', max_length=50),
        ),
    ]
