# Generated by Django 5.0.3 on 2024-03-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='role_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='role_name',
            new_name='name',
        ),
    ]
