# Generated by Django 3.2.25 on 2024-04-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_document_criticality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='criticality',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=50),
        ),
    ]
