# Generated by Django 3.2.25 on 2024-04-15 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0004_alter_document_criticality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentaccessrequest',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='documentaccessrequest',
            name='request_employees',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentaccessrequest',
            name='request_groups',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='documentaccessrequest',
            name='requested_permission',
            field=models.CharField(choices=[('view_document', 'View Document'), ('change_document', 'Change Document'), ('delete_document', 'Delete Document')], default='view_document', max_length=100),
        ),
        migrations.AlterField(
            model_name='documentaccessrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentaccessrequest',
            name='reason_given',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
