# Generated by Django 5.0.3 on 2024-03-18 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAccessRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason_given', models.CharField(max_length=500, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.document')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employee')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to='home.employee')),
            ],
        ),
    ]
