# Generated by Django 3.2.25 on 2024-04-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20240415_0148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pending',
        ),
        migrations.AddField(
            model_name='documentaccessrequest',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
