# Generated by Django 3.2.25 on 2024-04-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20240415_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentaccessrequest',
            name='requested_permission',
            field=models.CharField(choices=[('add_document', 'Upload Document'), ('view_document', 'View Document'), ('change_document', 'Change Document'), ('delete_document', 'Delete Document')], default='view_document', max_length=100),
        ),
    ]
