# Generated by Django 5.0.3 on 2024-03-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_employee_middle_name_alter_document_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
