# Generated by Django 3.2.25 on 2024-04-23 13:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20240422_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='delete_at',
            field=models.DateTimeField(default=datetime.datetime(2031, 4, 22, 13, 20, 35, 255084, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='documentaccessrequest',
            name='requested_permission',
            field=models.CharField(choices=[('add_document', 'Upload Document'), ('view_document', 'View Document'), ('edit_document', 'Edit Document'), ('delete_document', 'Delete Document')], default='view_document', max_length=100),
        ),
        migrations.CreateModel(
            name='DocumentAuditTrail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(default='upload', max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(max_length=2000)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.document')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
