# Generated by Django 5.0.3 on 2024-04-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_document_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('request', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('due_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
