# Generated by Django 5.0.3 on 2024-04-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='security_level',
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(default='yes.png', upload_to=''),
        ),
    ]
